# Site settings
name: rymai.me
description: "Web development stuff in english, philosophy/lifestyle thoughts in french!"
meta_description: "Web development stuff in english, philosophy/lifestyle thoughts in french!"
root_url: https://www.rymai.me
permalink: /:year/:month/:day/:title/
repository_url: https://gitlab.com/rymai/rymai.gitlab.io

google_analytics_id: UA-34888761-1

paginate: 5
paginate_path: ':num'

# Build settings, exclude vendor (this is where Gems are installed during CI build)
exclude: [CNAME, Gemfile, Gemfile.lock, Guardfile, README.md, sass, vendor]
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
# These are the default on GitHub Pages:
# https://help.github.com/articles/configuring-jekyll/#defaults-you-can-change
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "rymai"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "rymai"
