exclude: [CNAME, Gemfile, Gemfile.lock, Guardfile, README.md, sass]
name: rymai.me
permalink: /:year/:month/:day/:title/
google_analytics_id: UA-34888761-1
root_url: http://www.rymai.me
github_username: rymai
twitter_username: rymai
markdown: kramdown
kramdown:
  input: GFM
# redcarpet:
#   extensions: ['no_intra_emphasis', 'autolink', 'strikethrough', 'space_after_headers']
paginate: 5
paginate_path: ':num'
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "rymai"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "rymai"
